### PR TITLE
Create info.txt

### PR DESCRIPTION
**Pull request by Jarvismahesh**
I upload my Project in the github plz approve...

### CODE REVIEW

**Comment by Jarvismahesh** [comment]
plz approve above project...

**Review by Purushothaman1962 — APPROVED** [review]
Ok fine add it.

**Comment by Sarabudheen** [comment]
ok approve..

**Review by Sarabudheen — APPROVED** [review]
You can merge it.

**Comment by Jarvismahesh** [comment]
Tq

**Pull request merged**
